Signing tool changes for V1 and V2 secure header for Cronus and Simics
- Enable SBE and HBBL firmware v1 and v2 secure header

- Generating HW key hash based on user input as below :
   - user input v1 (default): HW key hash for v1 secure header
   - user input v2: HW key hash for v2 secure header
   - Note: Default generating for v1 secure header in case no user input

- In this commit sbh_firmware ,sbh_hbbl and sb_settings enabled

- Given example for sbh_firmware ( calculation will be same for HBBL also)

  sbh_firmware =  v1 secure header (size:1288) +
                  v2 secure header (size:15360)

  sbh_firmware = 1288 + 15360
  sbh_firmware = 16648 (size in byte)

- sb_settings frame formate is 72 byte as below
   HW key hash (64 byte ) + secure version(SV) (1 byte) +
   SB Mode (1 byte) + reserved bytes( 6 byte)
   sb_settings = 64 + 1 + 1 + 6 = 72 (size in byte)

- Below log taken from sbe seeprom binary report
   .sbh_firmware    8       0    0x0004f5a0   0x000536a7   0x00004108 (16648)
   .sbh_hbbl        8       0    0x0004b498   0x0004f59f   0x00004108 (16648)
   .sb_settings     1       0    0x000536a8   0x000536ef   0x00000048 (72)

JIRA: PFSBE-363

Change-Id: I38bf616b42acc74f7cb708805f1f89983a9d2c61
Reviewed-on: http://rchgit01.rchland.ibm.com/gerrit1/c/hw/ppe/+/174495
Tested-by: Jenkins OP Build CI <op-jenkins+hostboot@us.ibm.com>
Tested-by: Jenkins OP HW <op-hw-jenkins+hostboot@us.ibm.com>
Reviewed-by: Rangaswamy H B <rangaswamy.h.b@ibm.com>
Tested-by: FSP CI Jenkins <fsp-CI-jenkins+hostboot@us.ibm.com>
Tested-by: PPE CI <ppe-ci+hostboot@us.ibm.com>
Reviewed-by: Chris Engel <cjengel@us.ibm.com>
Reviewed-by: Sunil Kumar <skumar8j@in.ibm.com>
Tested-by: Jenkins Server <pfd-jenkins+hostboot@us.ibm.com>
Reviewed-by: Akhilesh S <akhis023@in.ibm.com>
Tested-by: Jenkins Combined Simics CI <combined-simics-ci+hostboot@us.ibm.com>

diff --git a/src/tools/scripts/signSbeImage b/src/tools/scripts/signSbeImage
--- a/src/tools/scripts/signSbeImage
+++ b/src/tools/scripts/signSbeImage
@@ -27,6 +27,9 @@
 # Exit if any command fails
 set -e
 
+# Tool version , Update tool version based on release
+TOOL_VERSION=1
+
 # @brief Checks whether the file that is the input argument exists on the file
 # system. The function
 #        exits with an error status if the file DNE.
@@ -70,12 +73,14 @@ alignFileSize()
 # @brief Print the help/usage info to the console
 usage()
 {
+    echo ""
     echo "Usage"
-    echo "!!!RUN ON A RHEL7 MACHINE!!!"
+    echo "!!!RUN ON A RHEL8 MACHINE!!!"
+    echo "TOOL VERSION : $TOOL_VERSION"
     echo "Sign SBE image"
     echo "signSbeImage -i <SBE image to sign> -t <IPL Image tool path> -s <scratch dir path> [-h ]"
     echo ""
-    echo "Options:"
+    echo "Options are as below......................"
     echo "  -h: print this message."
     echo "  -s: scratch dir path."
     echo "  -i: SBE image to sign. "
@@ -84,9 +89,10 @@ usage()
     echo "  -b: Build Type PNOR/STANDALONE (Default PNOR)."
     echo "  -d: SBE Image Dir path in op-build"
     echo "  -f: signing Mode. Production/Development(Default)"
+    echo "  -v: Secure Boot Mode is v1/v2(v1 is default)"
 }
 
-while getopts "h?s:i:t:b:d:S:f:" opt;
+while getopts "h?s:i:t:b:d:S:f:v:" opt;
 do
     case $opt in
 
@@ -123,6 +129,10 @@ do
             SIGNING_MODE=$OPTARG
         ;;
 
+        v)
+            SECUREBOOT_MODE=$OPTARG
+        ;;
+
         *)
             echo "Bad option: $OPTARG"
             usage
@@ -156,27 +166,60 @@ if [ -z $BUILD_TYPE ]; then
     BUILD_TYPE="PNOR" #Default Build Type
 fi
 
+if [ -z $SECUREBOOT_MODE ]; then
+    echo "***INFO | SBE | signSbeImage : Secure Boot Mode not entered. Defaulting v1 secure header"
+    SECUREBOOT_MODE="${SECUREBOOT_MODE:-v1}" #Default Secure Boot Mode (v1 secure header).
+fi
+
+# Secure boot mode, it could be either v1 or v2
+echo "***INFO | SBE | signSbeImage : Secure boot mode ... $SECUREBOOT_MODE"
+
+# Based on user input , selecting secure boot mode , default is v1 secure mode
+# Note: No other input expected from user apart from v1 or v2
+if [ "$SECUREBOOT_MODE" == "v1" ]; then
+    # If v1 secure header Secure Boot Mode => 0x0
+    SB_MODE="\x00"
+
+elif [ "$SECUREBOOT_MODE" == "v2" ] ;then
+    # If v2 secure header Secure Boot Mode => 0x1
+    SB_MODE="\x01"
+
+else
+    echo "***ERROR | SBE | signSbeImage : Invalid secure boot mode : $SECUREBOOT_MODE. Please supply the -v option."
+    usage
+    exit -1
+fi
+
 SIGNING_DIR=
-DEV_KEY_DIR=
-SIGNTOOL_ARGS=
+V1_DEV_KEY_DIR=
+V2_DEV_KEY_DIR=
+V1_SIGNTOOL_ARGS=
+V2_SIGNTOOL_ARGS=
 
 # Determine if our path setup has been provided by the environment
 if [ ! -z $SIGNING_BASE_DIR ]; then
-    echo "***INFO | SBE | signSbeImage : Fetching signing tools from provided environment"
+    echo "***INFO | SBE | signSbeImage : Fetching signing tools from provided environment for V1/v2 signing"
     RH_DIR=`sed "s/^.*release \([0-9]*\)\..*$/rh\1/" /etc/redhat-release`
     SIGNING_DIR=$SIGNING_BASE_DIR/$RH_DIR/$SIGNING_UTILS_DIR
-    DEV_KEY_DIR=${SIGNING_BASE_DIR}/sb-signing-keys
+    V1_DEV_KEY_DIR=${SIGNING_BASE_DIR}/sb-signing-keys
 
 elif [ -z $SBE_IMG_DIR_OP ]; then
-    echo "***INFO | SBE | signSbeImage : Not OP_build. Fetching keys and signing scripts from /afs/..."
-    RH_DIR=`sed 's/^.*release \([0-9]*\)\..*$/rh\1/' /etc/redhat-release`
-    DEV_KEY_DIR=/afs/rchland.ibm.com/projects/esw/bin/sb-signing/sb-signing-keys/
-    SIGNING_DIR=/afs/rchland.ibm.com/projects/esw/bin/sb-signing/$RH_DIR/sb-signing-utils
+
+    if [ -n $SIGNING_RHEL_PATH ]; then
+        echo "***INFO | SBE | signSbeImage : Not OP_build. Fetching keys and signing scripts."
+        V1_DEV_KEY_DIR=${SIGNING_RHEL_PATH}/sb-signing-utils/test/keys/
+        V2_DEV_KEY_DIR=${SIGNING_RHEL_PATH}/sb-signing-utils/test/v2_keys/
+        SIGNING_DIR=${SIGNING_RHEL_PATH}/bin/
+    else
+        echo "***ERROR | SBE | SIGNING_RHEL_PATH env var is not defined"
+        exit 1
+    fi
 
 else
     echo "***INFO | SBE | signSbeImage : OP_build. Fetching keys and signing scripts from OP-Build Tree"
-    DEV_KEY_DIR=${SBE_IMG_DIR_OP}/../../../host/etc/keys/
-    SIGNING_DIR=${SBE_IMG_DIR_OP}/../../../host/usr/bin/
+    V1_DEV_KEY_DIR=${HOST_DIR}/etc/keys/
+    V2_DEV_KEY_DIR=${HOST_DIR}/etc/v2_keys/
+    SIGNING_DIR=${HOST_DIR}/usr/bin/
 fi
 
 # Adjust paths to pick up the signing tools
@@ -191,18 +234,26 @@ if [ ! -z $BR2_OPENPOWER_P10_SECUREBOOT_SIGN_MODE ]; then
 elif [ ! -z $BR2_OPENPOWER_SECUREBOOT_SIGN_MODE ]; then
     SIGNING_MODE=$BR2_OPENPOWER_SECUREBOOT_SIGN_MODE
 
-#Check if user has passed signing mode
+# Check if user has passed signing mode
 elif [ -z $SIGNING_MODE ]; then
     SIGNING_MODE="Development"
     echo "***INFO | SBE | signSbeImage : Defaulting signing mode to $SIGNING_MODE "
 fi
 
+# For P11 we will always do v1 as dev signing.
+V1_SIGNTOOL_ARGS="$V1_SIGNTOOL_ARGS --mode development --flags 0x40080000 \
+                --hwKeyA ${V1_DEV_KEY_DIR}/hw_key_a.key --hwKeyB ${V1_DEV_KEY_DIR}/hw_key_b.key \
+                --hwKeyC ${V1_DEV_KEY_DIR}/hw_key_c.key --swKeyP ${V1_DEV_KEY_DIR}/sw_key_p.key "
+
 #Set flag basis Development or production mode.
+# Only v2 will be production signed.
 if [ "$SIGNING_MODE" = "Development" ]; then
     echo "***INFO | SBE | signSbeImage : Development Mode Signing"
-    SIGNTOOL_ARGS="$SIGNTOOL_ARGS --mode development --flags 0x40080000 \
-                   --hwKeyA ${DEV_KEY_DIR}/hw_key_a.key --hwKeyB ${DEV_KEY_DIR}/hw_key_b.key \
-                   --hwKeyC ${DEV_KEY_DIR}/hw_key_c.key --swKeyP ${DEV_KEY_DIR}/sw_key_a.key "
+    V2_SIGNTOOL_ARGS="$V2_SIGNTOOL_ARGS --mode development --flags 0x40080000 \
+                    --hwKeyA ${V2_DEV_KEY_DIR}/runtime_hw_key_a.key  \
+                    --hwKeyD ${V2_DEV_KEY_DIR}/runtime_hw_key_d.key  \
+                    --swKeyP ${V2_DEV_KEY_DIR}/runtime_sw_key_p.key  \
+                    --swKeyS ${V2_DEV_KEY_DIR}/runtime_sw_key_s.key  "
 
 elif [ "$SIGNING_MODE" = "Production" ] ||
      [ "$SIGNING_MODE" = "production" ]; then
@@ -217,13 +268,12 @@ elif [ "$SIGNING_MODE" = "Production" ] ||
         exit -1
     fi
 
-    SIGNTOOL_ARGS="$SIGNTOOL_ARGS --mode production --flags 0x40000000 \
-                   --hwKeyA __getkey --hwKeyB __getkey --hwKeyC __getkey --swKeyP __get \
-                   --sign-project-config $SB_PROJECT_INI --archiveIn $SB_ARCHIVE_IN"
+    V2_SIGNTOOL_ARGS="$V2_SIGNTOOL_ARGS --mode production --flags 0x40000000 \
+                --hwKeyA __getkey --hwKeyD __getkey --swKeyP __get --swKeyS __get \
+                --sign-project-config $SB_PROJECT_INI --archiveIn $SB_ARCHIVE_IN"
 
     # Need path to SF client to access signing server
     PATH=$SIGNING_DIR/../sb-signing-framework/sb-signing-framework/src/client:$PATH
-
 
 else
     echo "***ERROR | SBE | signSbeImage : Invalid signing mode option: $SIGNING_MODE. Enter correct -f option"
@@ -231,7 +281,7 @@ else
     exit -1
 fi
 
-#Determine secure version setting
+# Determine secure version setting
 if [ -z $SV ]; then
     # Build process can pass in the secure version through the environment
     if [ ! -z $SIGNING_SECURITY_VERSION ]; then
@@ -251,10 +301,14 @@ else
 fi
 
 # Do some sanity checks on things we expect the script to consume
-check_path ${DEV_KEY_DIR}/hw_key_a.key
-check_path ${DEV_KEY_DIR}/hw_key_b.key
-check_path ${DEV_KEY_DIR}/hw_key_c.key
-check_path ${DEV_KEY_DIR}/sw_key_a.key
+check_path ${V1_DEV_KEY_DIR}/hw_key_a.key
+check_path ${V1_DEV_KEY_DIR}/hw_key_b.key
+check_path ${V1_DEV_KEY_DIR}/hw_key_c.key
+check_path ${V1_DEV_KEY_DIR}/sw_key_p.key
+check_path ${V2_DEV_KEY_DIR}/runtime_hw_key_a.key
+check_path ${V2_DEV_KEY_DIR}/runtime_hw_key_d.key
+check_path ${V2_DEV_KEY_DIR}/runtime_sw_key_p.key
+check_path ${V2_DEV_KEY_DIR}/runtime_sw_key_s.key
 check_path ${IPL_IMAGE_TOOL}
 check_path ${SBEBINSIMIMAGE}
 check_path ${SIGNING_DIR}/crtSignedContainer.sh
@@ -266,23 +320,41 @@ printf "\nSign SBE Image\n"
 
 if [ "$BUILD_TYPE" = "STANDALONE" ]; then
 
-    #Extract .hbbl section from SBE image
+    # Extract .hbbl section from SBE image
     $IPL_IMAGE_TOOL $SBEBINSIMIMAGE extract .hbbl $SCRATCH_DIR/hbbl.bin || exit -1
 
     # Sign the .hbbl binary
     echo "Sign .hbbl section"
-    $SIGNING_DIR/crtSignedContainer.sh --scratchDir ${SCRATCH_DIR} $SIGNTOOL_ARGS \
-       --sign-project-FW-token HBBL --protectedPayload ${SCRATCH_DIR}/hbbl.bin \
-       --contrHdrOut ${SCRATCH_DIR}/SBE_HBBL.header --out ${SCRATCH_DIR}/SBE_HBBL.protected_payload.bin \
-       --validate --security-version $SV
+    # Sign the .hbbl binary for v1
+    CMD="$SIGNING_DIR/crtSignedContainer.sh --scratchDir ${SCRATCH_DIR} $V1_SIGNTOOL_ARGS \
+        --sign-project-FW-token HBBL --protectedPayload ${SCRATCH_DIR}/hbbl.bin \
+        --contrHdrOut ${SCRATCH_DIR}/V1_SBE_HBBL.header \
+        --security-version $SV --validate -V 1"
+    echo "$CMD"
+    $CMD
 
     #Strip out padding zeros from SBE_HBBL.header i.e only 1282 bytes is actual data. Keep it 8 byte alligned i.e 1288
     echo "Strip SBE_HBBL.header content"
-    dd bs=1 count=1288 if=${SCRATCH_DIR}/SBE_HBBL.header of=${SCRATCH_DIR}/SBE_HBBL_stripped.header
+    dd bs=1 count=1288 if=${SCRATCH_DIR}/V1_SBE_HBBL.header of=${SCRATCH_DIR}/V1_SBE_HBBL_stripped.header
 
-    #Append the stripped SBE_HBBL_stripped.header into .sbh_hbbl xip section
+    # copy v1 secure header content in final header file
+    cat ${SCRATCH_DIR}/V1_SBE_HBBL_stripped.header > ${SCRATCH_DIR}/V1_V2_HBBL_FW_SECURE.header
+
+    # Sign the .hbbl binary for v2
+    CMD="$SIGNING_DIR/crtSignedContainer.sh --scratchDir ${SCRATCH_DIR} $V2_SIGNTOOL_ARGS \
+        --sign-project-FW-token HBBL --protectedPayload ${SCRATCH_DIR}/hbbl.bin \
+        --contrHdrOut ${SCRATCH_DIR}/V2_SBE_HBBL.header \
+        --security-version $SV --validate -V 2"
+    echo "$CMD"
+    $CMD
+
+    # Appending v2 secure header in final header file
+    cat ${SCRATCH_DIR}/V2_SBE_HBBL.header >> ${SCRATCH_DIR}/V1_V2_HBBL_FW_SECURE.header
+
+    # Append the stripped V1_V2_HBBL_FW_SECURE.header into .sbh_hbbl xip section
     echo "Appending secure header into .sbh_hbbl xip section"
-    $IPL_IMAGE_TOOL $SBEBINSIMIMAGE append .sbh_hbbl $SCRATCH_DIR/SBE_HBBL_stripped.header || exit -1
+    $IPL_IMAGE_TOOL $SBEBINSIMIMAGE delete .sbh_hbbl
+    $IPL_IMAGE_TOOL $SBEBINSIMIMAGE append .sbh_hbbl $SCRATCH_DIR/V1_V2_HBBL_FW_SECURE.header || exit -1
 
 elif [ "$BUILD_TYPE" = "PNOR" ]; then
 
@@ -296,37 +368,54 @@ else
 
 fi
 
-#Extract .base section from SBE image
+# Extract .base section from SBE image
 $IPL_IMAGE_TOOL $SBEBINSIMIMAGE extract .base $SCRATCH_DIR/base.bin || exit -1
 
-#Align all files which are related to FW secure HDR to overcome alignment issues
-#during SHA512 calculation in verification process.
+# Align all files which are related to FW secure HDR to overcome alignment issues
+# During sha2-512 and sha3-512 calculation in verification process.
 alignFileSize $SCRATCH_DIR/base.bin
 
 # Rename base.bin to sbe_fw.bin
 mv $SCRATCH_DIR/base.bin $SCRATCH_DIR/sbe_fw.bin
 
-# Sign the SBE firmware binary image(payload.bin)
-CMD="$SIGNING_DIR/crtSignedContainer.sh --scratchDir ${SCRATCH_DIR} $SIGNTOOL_ARGS \
+# Sign the SBE firmware binary image(payload.bin) for v1 secure header
+CMD="$SIGNING_DIR/crtSignedContainer.sh --scratchDir ${SCRATCH_DIR} $V1_SIGNTOOL_ARGS \
     --sign-project-FW-token SBE_FW --protectedPayload ${SCRATCH_DIR}/sbe_fw.bin \
-    --contrHdrOut ${SCRATCH_DIR}/SBE_FW.header --out ${SCRATCH_DIR}/SBE_FW.protected_payload.bin \
-    --validate --security-version $SV"
-echo "Sign SBE FW image : $CMD"
+    --contrHdrOut ${SCRATCH_DIR}/V1_SBE_FW.header \
+    --security-version $SV --validate -V 1"
+echo "$CMD"
 $CMD
 
-#Strip out padding zeros from SBE_FW.header i.e only 1282 bytes is actual data. Keep it 8 byte alligned i.e 1288
-echo "Strip SBE_FW.header content"
-dd bs=1 count=1288 if=${SCRATCH_DIR}/SBE_FW.header of=${SCRATCH_DIR}/SBE_FW_stripped.header
+# Strip out padding zeros from V1_SBE_FW.header i.e only 1282 bytes is actual data. Keep it 8 byte alligned i.e 1288
+echo "Strip V1_SBE_FW.header content"
+dd bs=1 count=1288 if=${SCRATCH_DIR}/V1_SBE_FW.header of=${SCRATCH_DIR}/V1_SBE_FW_stripped.header
 
-#Append the stripped SBE_FW_stripped.header into .sbh_firmware xip section
+# Copy v1 secure header content in final header file
+cat ${SCRATCH_DIR}/V1_SBE_FW_stripped.header > ${SCRATCH_DIR}/V1_V2_SBE_FW_SECURE.header
+
+# Sign the SBE firmware binary image(payload.bin) for v2 secure header
+CMD="$SIGNING_DIR/crtSignedContainer.sh --scratchDir ${SCRATCH_DIR} $V2_SIGNTOOL_ARGS \
+    --sign-project-FW-token SBE_FW --protectedPayload ${SCRATCH_DIR}/sbe_fw.bin \
+    --contrHdrOut ${SCRATCH_DIR}/V2_SBE_FW.header \
+    --security-version $SV --validate -V 2"
+echo "$CMD"
+$CMD
+
+# Appending v2 secure header in final header file
+cat ${SCRATCH_DIR}/V2_SBE_FW.header >> ${SCRATCH_DIR}/V1_V2_SBE_FW_SECURE.header
+
+# Append the V1_V2_SBE_FW_SECURE.header into .sbh_firmware xip section
 echo "Appending secure header into .sbh_firmware xip section"
 $IPL_IMAGE_TOOL $SBEBINSIMIMAGE delete .sbh_firmware
-$IPL_IMAGE_TOOL $SBEBINSIMIMAGE append .sbh_firmware $SCRATCH_DIR/SBE_FW_stripped.header || exit -1
+$IPL_IMAGE_TOOL $SBEBINSIMIMAGE append .sbh_firmware $SCRATCH_DIR/V1_V2_SBE_FW_SECURE.header || exit -1
 
-#Hash of the HW keys. Fetch the value from any of the secure container which is created.
-#We need to filter out the HW keys from the print container output and convert the output to .bin format
-echo "Calculate/Fetch Hash of HW keys"
-print-container -w0 --imagefile ${SCRATCH_DIR}/SBE_FW.header | grep -A1 "HW keys hash" | grep "           " | head -1 | tr -d " " | tr -d "\n" | xxd -r -p > $SCRATCH_DIR/hw_keys_hash.bin
+# Converting secure boot mode from lower case to upper case
+# To simplifies HW key has generation for v1 and v2
+declare -u HW_KEY_HASH=$SECUREBOOT_MODE
+
+# Hash of the HW keys. Fetch the value from any of the secure container which is created.
+# We need to filter out the HW keys from the print container output and convert the output to .bin format
+print-container -w0 --imagefile ${SCRATCH_DIR}/${HW_KEY_HASH}_SBE_FW.header | grep -A1 "HW keys hash" | grep "           " | head -1 | tr -d " " | tr -d "\n" | xxd -r -p > $SCRATCH_DIR/hw_keys_hash.bin
 
 # Append minimum secure version(MSV), SB Mode and reserved bytes
 # into .sb_settings xip section after HW key hash
@@ -335,20 +424,16 @@ RESERVED="\x00\x00\x00\x00\x00\x00"
 SB_SV=`printf %02x $SV`
 SB_SV="\x${SB_SV}"
 
-# SB_Mode => Secure Boot Mode => 0x0 if v1 secure header 0x1 if v2 secure header
-# For p10 we only support v1 secure header format and hence hardcoding it to 0x0
-SB_MODE="\x00"
-
 echo "Appending SV $SB_SV, SB Mode $SB_MODE and reserved bytes $RESERVED to .sb_settings"
 echo -n -e $SB_SV$SB_MODE$RESERVED >> $SCRATCH_DIR/hw_keys_hash.bin
 echo $SCRATCH_DIR
 
-#Append the HW key hash into .sb_settings xip section
+# Append the HW key hash into .sb_settings xip section
 echo "Appending HW key hash into .sb_settings xip section"
 $IPL_IMAGE_TOOL $SBEBINSIMIMAGE delete .sb_settings
 $IPL_IMAGE_TOOL $SBEBINSIMIMAGE append .sb_settings $SCRATCH_DIR/hw_keys_hash.bin || exit -1
 
-#Lets delete the scratch dir
+# Lets delete the scratch dir
 rm -rf $SCRATCH_DIR
 
 echo "SBE Image Signed Successfully"
