AXONE Bringup CI
Change-Id: I611879498fe0b728547209716cecf6d940a9a820
Reviewed-on: http://rchgit01.rchland.ibm.com/gerrit1/72837
Tested-by: Jenkins Server <pfd-jenkins+hostboot@us.ibm.com>
Tested-by: FSP CI Jenkins <fsp-CI-jenkins+hostboot@us.ibm.com>
Reviewed-by: RAJA DAS <rajadas2@in.ibm.com>

diff --git a/src/test/framework/build-script b/src/test/framework/build-script
--- a/src/test/framework/build-script
+++ b/src/test/framework/build-script
@@ -6,7 +6,7 @@
 #
 # OpenPOWER sbe Project
 #
-# Contributors Listed Below - COPYRIGHT 2015,2018
+# Contributors Listed Below - COPYRIGHT 2015,2019
 # [+] International Business Machines Corp.
 #
 #
@@ -41,32 +41,38 @@ source "$SBEROOT/src/test/framework/setup-env"
 # Build SEEPROM Image
 bash -c  "make install -j" || exit -1
 
-# Create simics sandbox.
-create-sandbox > create-sandbox.log 2>&1 &
-CREATESANDBOX_PID=$!
+while read -d ':' p; do
 
-# Check sandbox create completion.
-wait $CREATESANDBOX_PID
-if [ $? -eq 0 ]; then
-    cat create-sandbox.log
-else
-    echo "----Sandbox creation failed."
-    cat create-sandbox.log
-    exit -1
-fi
+    export MACHINE_TYPE="$p"
+    echo "Setting up test simics for machine: '$MACHINE_TYPE'"
 
-# Add SBE files to simics sandbox.
-populate-sandbox || exit -1
+    # Create simics sandbox.
+    create-sandbox > create-sandbox.log 2>&1 &
+    CREATESANDBOX_PID=$!
 
-sbetest-start.sh || exit -1
+    # Check sandbox create completion.
+    wait $CREATESANDBOX_PID
+    if [ $? -eq 0 ]; then
+        cat create-sandbox.log
+    else
+        echo "----Sandbox creation failed."
+        cat create-sandbox.log
+        exit -1
+    fi
 
-# Check copyright completion.
-#wait $COPYRIGHT_PID
-#if [ $? -eq 0 ]; then
-#    cat copyright.log
-#else
-#    echo "----Copyright check failed."
-#    cat copyright.log
-#    exit -1
-#fi
+    # Add SBE files to simics sandbox.
+    populate-sandbox || exit -1
 
+    sbetest-start.sh || exit -1
+
+    # Check copyright completion.
+    #wait $COPYRIGHT_PID
+    #if [ $? -eq 0 ]; then
+    #    cat copyright.log
+    #else
+    #    echo "----Copyright check failed."
+    #    cat copyright.log
+    #    exit -1
+    #fi
+
+done <<< "$MACHINE:"
