Adding the Hooks and supporting files for commit and applypatch
Change-Id: Id6ea19f7c5acd6345d403fd3575d660f14647cd2
RTC:149657
Reviewed-on: http://ralgit01.raleigh.ibm.com/gerrit1/23406
Tested-by: Jenkins Server
Reviewed-by: Sachin Gupta <sgupta2m@in.ibm.com>

diff --git a/sbe/build/citest/build-script b/sbe/build/citest/build-script
--- a/sbe/build/citest/build-script
+++ b/sbe/build/citest/build-script
@@ -1,4 +1,28 @@
 #!/bin/sh
+# IBM_PROLOG_BEGIN_TAG
+# This is an automatically generated prolog.
+#
+# $Source: sbe/build/citest/build-script $
+#
+# OpenPOWER sbe Project
+#
+# Contributors Listed Below - COPYRIGHT 2015,2016
+# [+] International Business Machines Corp.
+#
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
+# implied. See the License for the specific language governing
+# permissions and limitations under the License.
+#
+# IBM_PROLOG_END_TAG
 
 if [ -z $WORKSPACE ]; then
     export WORKSPACE=`pwd`
@@ -10,11 +34,9 @@ fi
 
 source "$SBEROOT/sbe/build/citest/setup-env"
 
-# @TODO via RTC 140875
-#Enable it once SBE copyright script is ready
 # Check copyright.
-#check-copyright > copyright.log 2>&1 &
-#COPYRIGHT_PID=$!
+check-copyright > copyright.log 2>&1 &
+COPYRIGHT_PID=$!
 
 
 # Build .
@@ -41,15 +63,13 @@ populate-sandbox || exit -1
 
 sbetest-start.sh || exit -1
 
-# @TODO via RTC 140875
-#Enable it once SBE copyright script is ready
 # Check copyright completion.
-#wait $COPYRIGHT_PID
-#if [ $? -eq 0 ]; then
-#    cat copyright.log
-#else
-#    echo "----Copyright check failed."
-#    cat copyright.log
-#    exit -1
-#fi
+wait $COPYRIGHT_PID
+if [ $? -eq 0 ]; then
+    cat copyright.log
+else
+    echo "----Copyright check failed."
+    cat copyright.log
+    exit -1
+fi
 
