Temporary disable the prolog verification in CI
Change-Id: Ia826a8a0c5a55acd1f94af979383c255815babf0
Reviewed-on: http://ralgit01.raleigh.ibm.com/gerrit1/25164
Tested-by: Jenkins Server
Reviewed-by: Sachin Gupta <sgupta2m@in.ibm.com>

diff --git a/sbe/build/citest/build-script b/sbe/build/citest/build-script
--- a/sbe/build/citest/build-script
+++ b/sbe/build/citest/build-script
@@ -35,8 +35,8 @@ fi
 source "$SBEROOT/sbe/build/citest/setup-env"
 
 # Check copyright.
-check-copyright > copyright.log 2>&1 &
-COPYRIGHT_PID=$!
+#check-copyright > copyright.log 2>&1 &
+#COPYRIGHT_PID=$!
 
 
 # Build .
@@ -64,12 +64,12 @@ populate-sandbox || exit -1
 sbetest-start.sh || exit -1
 
 # Check copyright completion.
-wait $COPYRIGHT_PID
-if [ $? -eq 0 ]; then
-    cat copyright.log
-else
-    echo "----Copyright check failed."
-    cat copyright.log
-    exit -1
-fi
+#wait $COPYRIGHT_PID
+#if [ $? -eq 0 ]; then
+#    cat copyright.log
+#else
+#    echo "----Copyright check failed."
+#    cat copyright.log
+#    exit -1
+#fi
 
